//! MU1 — workspace invitations.
//!
//! Spec: [[workspace-invitations]] memory entry + (TODO)
//! `docs/research/18-workspace-invitations.md`.
//!
//! The token is a 32-byte URL-safe base64 string, generated by the
//! HTTP handler when creating the row. We never compare tokens with
//! `LIKE` — `find_by_token` uses the indexed equality lookup so a
//! malicious party can't brute-force by prefix.
//!
//! Acceptance rules (enforced by the HTTP handler, not the repo):
//!
//! - `revoked_at` is null
//! - `expires_at` is null OR > now()
//! - `used_count < max_uses`
//!
//! The repo exposes the fields and the handler decides.

use serde::{Deserialize, Serialize};
use sqlx::Row;

use crate::{
    users::{parse_ts, ts},
    Db, DbError,
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkspaceInvitation {
    pub id: String,
    pub workspace_id: String,
    pub token: String,
    pub role: String,
    pub created_by: String,
    pub created_at: time::OffsetDateTime,
    pub expires_at: Option<time::OffsetDateTime>,
    pub max_uses: i64,
    pub used_count: i64,
    pub revoked_at: Option<time::OffsetDateTime>,
}

impl WorkspaceInvitation {
    /// True when the invitation has used up every slot, expired, or
    /// been revoked. The accept handler checks this before admitting.
    #[must_use]
    pub fn is_consumable(&self) -> bool {
        if self.revoked_at.is_some() {
            return false;
        }
        if self
            .expires_at
            .is_some_and(|t| t < time::OffsetDateTime::now_utc())
        {
            return false;
        }
        self.used_count < self.max_uses
    }
}

#[derive(Debug, Clone)]
pub struct NewWorkspaceInvitation {
    pub workspace_id: String,
    pub token: String,
    pub role: String,
    pub created_by: String,
    pub expires_at: Option<time::OffsetDateTime>,
    pub max_uses: i64,
}

#[derive(Debug, Clone)]
pub struct WorkspaceInvitationRepo<'a> {
    db: &'a Db,
}

impl<'a> WorkspaceInvitationRepo<'a> {
    #[must_use]
    pub fn new(db: &'a Db) -> Self {
        Self { db }
    }

    pub async fn insert(
        &self,
        new: &NewWorkspaceInvitation,
    ) -> Result<WorkspaceInvitation, DbError> {
        let id = ulid::Ulid::new().to_string();
        let created_at = time::OffsetDateTime::now_utc();
        sqlx::query(
            "INSERT INTO workspace_invitations \
             (id, workspace_id, token, role, created_by, created_at, expires_at, \
              max_uses, used_count, revoked_at) \
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, NULL)",
        )
        .bind(&id)
        .bind(&new.workspace_id)
        .bind(&new.token)
        .bind(&new.role)
        .bind(&new.created_by)
        .bind(ts(created_at))
        .bind(new.expires_at.map(ts))
        .bind(new.max_uses)
        .execute(self.db.pool())
        .await?;

        Ok(WorkspaceInvitation {
            id,
            workspace_id: new.workspace_id.clone(),
            token: new.token.clone(),
            role: new.role.clone(),
            created_by: new.created_by.clone(),
            created_at,
            expires_at: new.expires_at,
            max_uses: new.max_uses,
            used_count: 0,
            revoked_at: None,
        })
    }

    /// Public-safe — used by the anonymous peek + accept endpoints.
    /// Equality-only on the indexed column so prefix attacks aren't
    /// a thing.
    pub async fn find_by_token(&self, token: &str) -> Result<WorkspaceInvitation, DbError> {
        let row = sqlx::query(
            "SELECT id, workspace_id, token, role, created_by, created_at, \
             expires_at, max_uses, used_count, revoked_at \
             FROM workspace_invitations WHERE token = ?",
        )
        .bind(token)
        .fetch_optional(self.db.pool())
        .await?;
        match row {
            Some(r) => row_to_invitation(&r),
            None => Err(DbError::NotFound),
        }
    }

    pub async fn list_for_workspace(
        &self,
        workspace_id: &str,
    ) -> Result<Vec<WorkspaceInvitation>, DbError> {
        let rows = sqlx::query(
            "SELECT id, workspace_id, token, role, created_by, created_at, \
             expires_at, max_uses, used_count, revoked_at \
             FROM workspace_invitations WHERE workspace_id = ? \
             ORDER BY created_at DESC",
        )
        .bind(workspace_id)
        .fetch_all(self.db.pool())
        .await?;
        rows.iter().map(row_to_invitation).collect()
    }

    pub async fn find_by_id(&self, id: &str) -> Result<WorkspaceInvitation, DbError> {
        let row = sqlx::query(
            "SELECT id, workspace_id, token, role, created_by, created_at, \
             expires_at, max_uses, used_count, revoked_at \
             FROM workspace_invitations WHERE id = ?",
        )
        .bind(id)
        .fetch_optional(self.db.pool())
        .await?;
        match row {
            Some(r) => row_to_invitation(&r),
            None => Err(DbError::NotFound),
        }
    }

    /// Revoke. Idempotent — setting `revoked_at` on an already-revoked
    /// row is a no-op from the consumer's perspective.
    pub async fn revoke(&self, id: &str) -> Result<(), DbError> {
        sqlx::query(
            "UPDATE workspace_invitations SET revoked_at = ? \
             WHERE id = ? AND revoked_at IS NULL",
        )
        .bind(ts(time::OffsetDateTime::now_utc()))
        .bind(id)
        .execute(self.db.pool())
        .await?;
        Ok(())
    }

    /// Atomic accept — increments `used_count` IFF the invitation is
    /// still consumable. Returns the updated row count; 1 means the
    /// caller has a slot, 0 means the invitation was exhausted /
    /// expired / revoked between the peek and the accept. Handlers
    /// pair this with the membership insert in a tx so partial
    /// acceptance is impossible.
    pub async fn try_consume(&self, id: &str) -> Result<u64, DbError> {
        let now = ts(time::OffsetDateTime::now_utc());
        let res = sqlx::query(
            "UPDATE workspace_invitations \
             SET used_count = used_count + 1 \
             WHERE id = ? \
               AND revoked_at IS NULL \
               AND (expires_at IS NULL OR expires_at > ?) \
               AND used_count < max_uses",
        )
        .bind(id)
        .bind(now)
        .execute(self.db.pool())
        .await?;
        Ok(res.rows_affected())
    }
}

fn row_to_invitation(row: &sqlx::any::AnyRow) -> Result<WorkspaceInvitation, DbError> {
    Ok(WorkspaceInvitation {
        id: row.get("id"),
        workspace_id: row.get("workspace_id"),
        token: row.get("token"),
        role: row.get("role"),
        created_by: row.get("created_by"),
        created_at: parse_ts(row.get::<String, _>("created_at"))?,
        expires_at: row
            .get::<Option<String>, _>("expires_at")
            .map(parse_ts)
            .transpose()?,
        max_uses: row.get("max_uses"),
        used_count: row.get("used_count"),
        revoked_at: row
            .get::<Option<String>, _>("revoked_at")
            .map(parse_ts)
            .transpose()?,
    })
}
